### ISSUE TITLE
Overclocking capabilities and fan settings borked.

### ISSUE THREAD

**Issue by ufoludekxyz** [NVIDIA/nvidia-settings#65] opened 2021-04-18 09:25 UTC
After the latest update I'm not longer able to OC nor change the fan curve on my GPU, be it via CLI or some GUI solutions like GWE. It worked on the previous versions.

Kernel: `5.11.15-arch1-2`
GPU: GTX 1070
Drivers: `nvidia`
Drivers version: `465.24.02-3`

**Comment by iamshadow2008** [comment] 2021-04-29 22:48
Same issue with kernel 5.11.16.arch1-1 and nvidia 465.27-1 on an RTX 2600

**Comment by iamshadow2008** [comment] 2021-05-05 18:40
> Same issue with kernel 5.11.16.arch1-1 and nvidia 465.27-1 on an RTX 2060
> 
> nvidia-settings GUI fails, CLI fails, GWE fails

fixed by adding to xorg.conf:
`allowed_users=anybody
needs_root_rights=yes
`
and calling:
`sudo chmod u+s /usr/lib/Xorg.wrap`

and rebooting

**Comment by jpestima** [comment] 2021-05-05 21:04
@iamshadow2008 yeah, my PC won't load xorg if I do that. Are you using GDM?

**Comment by iamshadow2008** [comment] 2021-05-05 21:25
@jpestima My bad, I meant to say it should go in /etc/X11/Xwrapper.config but I wrote xorg.conf by mistake.

**Comment by jpestima** [comment] 2021-05-05 21:29
@iamshadow2008 Thanks :) Do I need to install any specific package or just to create the file? I am using arch.

Also, is this sudo chmod u+s /usr/lib/Xorg.wrap really necessary?

**Comment by iamshadow2008** [comment] 2021-05-05 21:31
> @iamshadow2008 Thanks :) Do I need to install any specific package or just to create the file? I am using arch.
> 
> Also, is this sudo chmod u+s /usr/lib/Xorg.wrap really necessary?

Just create the file. And it may not be necessary for you, but in my case it was. Without chmod u+s, the Xwrapper.config entries were ignored and GDM started xorg as my user.

**Comment by jpestima** [comment] 2021-05-05 22:41
@iamshadow2008 Thanks for the info man, it worked out for me. 

Currently running version 465.27, fans and OC are working as intended.

I just had to do an additional step, as my Xorg.wrap was already modified by the system. I had to reinstall xorg server

Steps where the following:

-  Add the above code code to /etc/X11/Xwrapper.config

**Comment by zbarn** [comment] 2021-05-07 04:50
> > Same issue with kernel 5.11.16.arch1-1 and nvidia 465.27-1 on an RTX 2060
> > nvidia-settings GUI fails, CLI fails, GWE fails
> 
> fixed by adding to /etc/X11/Xwrapper.config:
> 
> ```
> allowed_users=anybody
> 
> needs_root_rights=yes
> ```
> 
> and calling:
> `sudo chmod u+s /usr/lib/Xorg.wrap`
> 
> and rebooting

Works great. Thank you.

**Comment by ufoludekxyz** [comment] 2021-05-12 22:15
Still broken after todays update, it has been 3 updates already...
Yes, I read the comments above, I don't want to run X as root, it's more of a bypass than a fix.

Kernel: `5.12.3-arch1-1`
GPU: GTX 1070
Drivers: nvidia
Drivers version: `5.12.3-arch1-1`

**Comment by marvic2409** [comment] 2021-05-12 22:18
Yeah I agree, but for my purposes it's fine. Hope nvidia can make a fix soon though

**Comment by aaronp24** [comment] 2021-05-13 00:57
I think this was an intentional change to prevent non-root users from changing settings that can impact interactivity for other users. I filed internal bug number 3309289 to request adding a way to open the permissions back up.

Closing this issue because nvidia-settings itself isn't responsible for this, it just forwards requests on to the rest of the driver.

**Closed by aaronp24** 2021-05-13 00:57 UTC

**Comment by rip057** [comment] 2021-06-17 02:12
this is still broken, i have heard running X as root is frowned upon...
any update?  
the latest driver i can run with the ability to change the fan is 455.45.01  maybe there is one after it, but this one works, but i cant install it with a later kernel.

**Comment by Razer0123** [comment] 2021-06-23 16:35
> this is still broken, i have heard running X as root is frowned upon...
> any update?
> the latest driver i can run with the ability to change the fan is 455.45.01 maybe there is one after it, but this one works, but i cant install it with a later kernel.

No update as far as i know, i am waiting for update 470 hoping it will help

**Comment by Razer0123** [comment] 2021-07-10 15:39
No news?

**Comment by gilvbp** [comment] 2021-07-16 17:10
@Razer0123 I have just upgraded to 470 and it's all ok good again :)

**Comment by Razer0123** [comment] 2021-07-21 09:54
> @Razer0123 I have just upgraded to 470 and it's all ok good again :)

People on the other thread are reporting the issue is still present

**Comment by rip057** [comment] 2021-07-22 01:09
The way I have dealt with this is ez

Start a shell as root:
CTRL-ALT-F2
startx
Inside x Windows use nvidia-settings as normal then log off and loh out of
that terminal...
go back to your regular terminal screen, ctrl-alt-f1, usually, and then
proceed as normal...

I only modify the fan to be on full blast, and it works great...

**Comment by VeselyJan92** [comment] 2021-07-31 09:43
The issue still persist on: Driver Version: 470.57.02 RTX 2080 Super (Zotac)

**Comment by mdeliu** [comment] 2021-11-14 15:51
This issue is still present.

GPU: Nvidia GTX 1080 (HP OEM)
OS: Fedora 35 Workstation (GNOME)
Kernel: Linux fedora 5.14.17-301.fc35.x86_64
Driver Version: 495.44


Adding following code under /etc/X11/Xwrapper.config (followed by a reboot) as mentioned by @iamshadow2008 did the trick for me. No need to sudo chmod u+s /usr/lib/Xorg.wrap (as the file doesn't exist on my installation). 

> ```
> allowed_users=anybody
> 
> needs_root_rights=yes
> ```

Keep in mind to add the correct coolbit value in the /etc/X11/xorg.conf (or any other config file for the Nvidia GPU).

**Comment by stevekm** [comment] 2022-10-19 01:55
> > Same issue with kernel 5.11.16.arch1-1 and nvidia 465.27-1 on an RTX 2060
> > nvidia-settings GUI fails, CLI fails, GWE fails
> 
> fixed by adding to /etc/X11/Xwrapper.config:
> 
> ```
> allowed_users=anybody
> 
> needs_root_rights=yes
> ```
> 
> and calling: `sudo chmod u+s /usr/lib/Xorg.wrap`
> 
> and rebooting


is that the same file as this?

```
$ ll /usr/lib/xorg/Xorg.wrap 
-rwsr-sr-x 1 root root 15K Jul  6 09:45 /usr/lib/xorg/Xorg.wrap
```

note that `xorg` is not caps here but `Xorg.wrap` is. Also it already appears to have these permission set. This is on Ubuntu 22.04
