### ISSUE TITLE
How to initialize Pixmap using blending datafile for WarpBlend API?

### ISSUE THREAD

**Issue by pranavkantgaur** [NVIDIA/nvidia-settings#33] opened 2018-10-17 12:43 UTC
Hi,

I have been trying to using Warp Blend API by customizing nv-control-warpblend.c sample code. I am reading warping and blending data for each display from separate data files. Warping is working fine(except times when same WarpMesh is allocated to multiple displays). Blending however is not working as expected. Following is my code with relevant line indicating how I have called API for blending:
https://gist.github.com/pranavkantgaur/70fa882e58311ed8eddc9c7fec78c0d3#file-nvcontrol-warp-blend-with-file-configuration-c-L264

What I see in my output is a displaced(wrt. neighbor displays) texture. **I would like to verify if I have initialized the pixmap correctly?**

**Comment by aritger** [comment] 2018-10-17 16:48
I think you want the x,y arguments to XFillRectangle() to be 0,0, not 1,1:

XFillRectangle(xDpy, blendPixmap, gc, 0, 0, displayWidth, displayHeight);

**Comment by pranavkantgaur** [comment] 2018-10-18 05:16
Thanks @aritger for pointing it out. However, I would like to take your advice on the correct way of initialization of **blendPixmap**(line 264): 
https://gist.github.com/pranavkantgaur/70fa882e58311ed8eddc9c7fec78c0d3#file-nvcontrol-warp-blend-with-file-configuration-c-L264

**Comment by aritger** [comment] 2018-10-18 16:18
I don't see an obvious problem with the XNVCTRLSetScanoutIntensity() call.  Depending on what you want to achieve, you might need to alter the 'blendAfterWarp' argument (the last argument).

If you continue to have problems, it might be worthwhile to stub out the warp part, and just experiment with blending.  Maybe also start with driving a single monitor, and experiment with that, then add more monitors.  That should hopefully help identify where the problem is.

**Comment by pranavkantgaur** [comment] 2018-10-31 11:48
@aritger Do I need to initialize XImage using a char array with 32 bits per pixel, even if the image depth is 24 bits, as suggested [here](https://groups.google.com/d/msg/comp.windows.x/SJt1Vyzv3nc/5LbedVfMyHIJ)?

**Comment by aritger** [comment] 2018-11-01 16:00
I don't know off hand about your displacement observations.

For your Ximage question: "depth" is the number of bits in each pixel that carry meaningful color data, and bits-per-pixel is the number of bits allocated for each pixel.  A very common layout is 32 bits-per-pixel (i.e., four bytes), but only 24 bits of depth (many GPUs, including NVIDIA, do not support packed 3 bytes per pixel, so each pixel is padded out to 4 bytes).

I hope that helps.

**Comment by pranavkantgaur** [comment] 2018-11-02 01:57
Thanks for the info regarding XImage. I will update this thread once I solve the problem.

**Comment by aaronp24** [comment] 2020-05-18 23:17
Closing as this doesn't seem like an issue with nvidia-settings itself. Please let me know if there turned out to actually be a problem with `nv-control-warpblend.c`.

**Closed by aaronp24** 2020-05-18 23:17 UTC
